# Welcome to Jekyll!


# Site settings
title: Mehank - blog
email: m3hank1337@gmail.com
description: Web-Application Pentester & Secure Code Reviewer
baseurl: ""
url: "https://m3hank.github.io/"
usernames:
  twitter: m3hank
  github:  m3hank
  linkedin: m3hank

permalink: pretty

# Build settings
markdown: kramdown
timezone: "+0530"

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: false
      mathjax:  false
      social:   true