# Site settings
title: "Your Blog Title"
description: "Write-ups of my bug and vulnerability findings."
url: "https://M3hank.github.io"

author:
  name: "Your Name"
  avatar: "/assets/images/avatar.png"  # Replace with a valid image or external URL
  bio: "Web Application Pentester"
  location: "Your Location"
  email: "your.email@example.com"

social_links:
  - name: "GitHub"
    url: "https://github.com/M3hank"
    icon: "fab fa-github"
  
  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/m3hank/"
    icon: "fab fa-linkedin"
  
  - name: "Twitter"
    url: "https://x.com/M3hank"
    icon: "fab fa-twitter"

skin: dark

nav:
  - title: "Home"
    url: "/"
  - title: "Blog"
    url: "/blog/"
  - title: "About"
    url: "/about/"

# Comments (Disqus)
comments:
  provider: "disqus"
  disqus:
    shortname: "your-disqus-shortname"  # Replace with your Disqus shortname

# Build settings
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache


# Exclude unnecessary files from being processed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
