# Site settings
title: "Your Name - Blog"
description: "Web Application Pentesting Writeups"
url: "https://M3hank.github.io"
author:
  name: "Your Name"
  bio: "Web Application Pentester"
  email: "your.email@example.com"

# Navigation links
nav:
  - title: "Projects"
    url: "/projects/"
  - title: "About"
    url: "/about/"

# Social links for footer
social_links:
  - name: "GitHub"
    url: "https://github.com/M3hank"
    icon: "fab fa-github"

  - name: "Twitter"
    url: "https://x.com/M3hank"
    icon: "fab fa-twitter"

  - name: "LinkedIn"
    url: "https://www.linkedin.com/in/m3hank/"
    icon: "fab fa-linkedin"

# Footer contact info
footer:
  email: "M3hank@example.com"
  name: "M3hank - Security & Automation Researcher"
  description: "Web Application Pentesting Writeups"

# Build settings
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# Use light skin (minimalistic look)
skin: "light"
